package com.aatmn2000.aibuilder.core.agent

import com.aatmn2000.aibuilder.core.ai.AiGateway
import com.aatmn2000.aibuilder.core.project.GeneratedProject
import com.aatmn2000.aibuilder.core.project.ProjectFile

/**
 * A specialized AI agent. Agents are stateless: they receive an
 * [AgentContext], talk to the AI through the gateway, and return the
 * artifacts they produced.
 */
interface Agent {
    val role: AgentRole

    fun run(context: AgentContext): AgentResult
}

/** Everything an agent needs to do its job. */
data class AgentContext(
    val gateway: AiGateway,
    val userRequest: String,
    /** The project being modified, or null when creating a new project. */
    val existingProject: GeneratedProject?,
    val profile: DomainProfile,
    val projectName: String,
    /** Files already generated by earlier agents in this run. */
    val generatedSoFar: List<ProjectFile> = emptyList()
)

/**
 * The outcome of one agent run: a human-readable summary plus the files
 * (artifacts) the agent produced.
 */
data class AgentResult(
    val role: AgentRole,
    val summary: String,
    val artifacts: List<ProjectFile> = emptyList(),
    val isError: Boolean = false,
    val errorDetail: String? = null
) {
    companion object {
        fun unavailable(role: AgentRole): AgentResult =
            AgentResult(
                role = role,
                summary = "${role.name} is not available in V1 (planned for V2)."
            )
    }
}
